#!/usr/bin/env bash
#Write a Bash script that create a file and delete that file
#and display message as requested
sudo sh -c 'echo $$ >> /var/run/holbertonscript.pid'
trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; kill -9 $$' SIGTERM
trap 'sudo rm /var/run/holbertonscript.pid' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
while true; do
echo "To infinity and beyond"
sleep 2
done
