#!/usr/bin/env bash
# for the good luck

i="1"
while (("$i" <= 10)); do
if (("$i" == 4)); then
    echo "bad luck"
elif (("$i" == 8)); then
    echo "good luck"
else
    echo "Holberton School"
fi
i=$((i + 1))
done
