#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with specific requirements
touch ~/hosts.new
cp /etc/hosts ~/hosts.new
sed -i 's/^127\.0\.0\.1.*/127.0.0.2 localhost/' ~/hosts.new
echo '8.8.8.8 facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
